<?php
/**
 * =============================================================================
 * Print Layout Footer
 * =============================================================================
 * Closes the print body and shows a printed-by footer line.
 * =============================================================================
 */
?>
</div><!-- /.print-body -->
<div class="print-footer no-print">
    Generated by <?php echo e(get_setting('site_name', 'Computer Lab Management System')); ?> on <?php echo date('d M Y H:i:s'); ?>
</div>
</body>
</html>
